package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"segura-cli/internal/config"
	"segura-cli/internal/webproxy"
)

const sshConfigTag = "# SEGURA-CLI ssh-config"

var sshConfigWrite bool

// sshConfigCmd generates ~/.ssh/config entries that route native ssh/scp/rsync/git
// to devices through the gateway, using `segura proxy` as a ProxyCommand.
var sshConfigCmd = &cobra.Command{
	Use:   "ssh-config",
	Short: "Generate ~/.ssh/config entries to reach devices with native ssh/scp/rsync",
	Long: `Generates OpenSSH client config entries (one Host per credential) that tunnel
native ssh/scp/rsync/git to your devices through the senhasegura gateway, using
'segura proxy' as a ProxyCommand.

By default the config is printed to stdout; use --write to append it to
~/.ssh/config inside an idempotent, tagged block.

Note on authentication: the tunnel gives native ssh a raw connection to the
device's SSH server — you then authenticate to the DEVICE with your own key or
password (segura injects the vault credential for its OWN sessions, not for the
native client). This is most useful where you have key-based access to devices.`,
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		cmd.SilenceUsage = true

		cfg, err := config.Load(envFile)
		if err != nil {
			return fmt.Errorf("configuration error: %w", err)
		}
		creds, err := webproxy.ListCredentials(cfg)
		if err != nil {
			return fmt.Errorf("could not load credentials: %w", err)
		}
		if len(creds) == 0 {
			return fmt.Errorf("no credentials found")
		}

		exe, err := os.Executable()
		if err != nil || exe == "" {
			exe = "segura"
		}

		block := renderSSHConfig(creds, exe)

		if !sshConfigWrite {
			fmt.Print(block)
			return nil
		}

		home, err := os.UserHomeDir()
		if err != nil {
			return err
		}
		cfgPath := filepath.Join(home, ".ssh", "config")
		if err := os.MkdirAll(filepath.Dir(cfgPath), 0o700); err != nil {
			return err
		}
		if err := replaceTaggedBlock(cfgPath, sshConfigTag, block); err != nil {
			return err
		}
		fmt.Printf("Wrote %d host entries to %s\n", len(creds), cfgPath)
		fmt.Println("Try:  ssh " + hostAlias(creds[0]))
		return nil
	},
}

// renderSSHConfig builds the tagged config block for all credentials.
func renderSSHConfig(creds []webproxy.Credential, exe string) string {
	// Stable order + de-dup aliases.
	sort.Slice(creds, func(i, j int) bool {
		return hostAlias(creds[i]) < hostAlias(creds[j])
	})
	seen := map[string]bool{}

	var b strings.Builder
	fmt.Fprintf(&b, "%s\n", sshConfigTag)
	fmt.Fprintf(&b, "# Generated by 'segura ssh-config'. Native ssh/scp/rsync via the PAM gateway.\n")
	fmt.Fprintf(&b, "# Device-side auth is your own (key/password on the device).\n")
	for _, c := range creds {
		alias := hostAlias(c)
		for seen[alias] {
			alias += "-2"
		}
		seen[alias] = true

		fmt.Fprintf(&b, "\nHost %s\n", alias)
		fmt.Fprintf(&b, "    HostName 127.0.0.1\n")
		fmt.Fprintf(&b, "    User %s\n", c.Username)
		fmt.Fprintf(&b, "    ProxyCommand %q proxy %s@%s\n", exe, c.Username, c.Device)
		fmt.Fprintf(&b, "    StrictHostKeyChecking no\n")
		fmt.Fprintf(&b, "    UserKnownHostsFile /dev/null\n")
	}
	fmt.Fprintf(&b, "%s end\n", sshConfigTag)
	return b.String()
}

// hostAlias builds a safe ssh Host alias like "segura-web01-root".
func hostAlias(c webproxy.Credential) string {
	dev := sanitizeAlias(c.Device)
	if dev == "" {
		dev = sanitizeAlias(c.IP)
	}
	return "segura-" + dev + "-" + sanitizeAlias(c.Username)
}

func sanitizeAlias(s string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(s) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == '.' || r == '-' || r == '_':
			b.WriteRune('-')
		default:
			b.WriteRune('-')
		}
	}
	return strings.Trim(b.String(), "-")
}

// replaceTaggedBlock replaces an existing tagged block in path (between "tag" and
// "tag end") or appends it if absent — so repeated runs stay idempotent.
func replaceTaggedBlock(path, tag, block string) error {
	data, _ := os.ReadFile(path)
	content := string(data)

	start := strings.Index(content, tag)
	if start >= 0 {
		endMarker := tag + " end"
		end := strings.Index(content, endMarker)
		if end >= start {
			end += len(endMarker)
			// consume a trailing newline if present
			if end < len(content) && content[end] == '\n' {
				end++
			}
			content = content[:start] + strings.TrimSuffix(block, "\n") + "\n" + content[end:]
			return os.WriteFile(path, []byte(content), 0o600)
		}
	}
	// append
	if len(content) > 0 && !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	content += "\n" + block
	return os.WriteFile(path, []byte(content), 0o600)
}

func init() {
	sshConfigCmd.Flags().BoolVar(&sshConfigWrite, "write", false, "Append/update the entries in ~/.ssh/config")
	rootCmd.AddCommand(sshConfigCmd)
}
